# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:   # Añadir esto para ejecutar manualmente
    inputs:
      branch:
        description: 'Branch to run'
        default: 'master'
        required: true

  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Remove existing settings.xml if it exists
      run: |
        if [ -f "${{ github.workspace }}/.github/settings.xml" ]; then
          echo "Removing existing settings.xml..."
          rm -f ${{ github.workspace }}/.github/settings.xml
        fi

    - name: Create settings.xml with credentials
      run: |
        echo "Creating settings.xml with credentials..."
        mkdir -p ${{ github.workspace }}/.github
        cat <<EOF >${{ github.workspace }}/.github/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}/.github/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.github/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
